### ISSUE TITLE
Error with 3.6.1 endpoints

### ISSUE THREAD

**Issue by JonHerke-TG** [TigerGraph-DevLabs/TG_Endpoints_to_Postman#1]
Post July 5th the endpoints changed from what is currently in the postman generated script:
`{{protocol}}://{{url}}:{{port}}/endpoints/{{graph_name}}`

to the following:
`{{protocol}}://{{url}}:{{port}}/restpp/endpoints`

Note the use of `/restpp/` in the URL string. 

You can find all those examples in this postman collection https://www.postman.com/tigergraph-dev/workspace/tigergraph-devs-s-public-workspace/collection/5802704-77f657e8-aeb7-4c5d-9dc1-40ace812f2e9?action=share&creator=10822498

**Comment by JonHerke-TG** [comment]
Maybe in the cred.py we also ask users to specify version?
`TGVersion: "3.6.1"`

**Comment by 01110011011101010110010001101111** [comment]
Thanks for opening the bug! Just opened https://github.com/TigerGraph-DevLabs/TG_Endpoints_to_Postman/pull/2 to automatically grab the version and add the `/restpp/` to the URL string. Tested on a 3.6.2 TG Cloud solution.

**Comment by 01110011011101010110010001101111** [comment]
Fixed in f0751f5f741357ba8927467724ae301149d82e4c.
